version: '3.9'
services:
  hrp:
    build:
      context: .
      dockerfile: ./apps/hrp/Dockerfile
      args:
        - appname=hrp
    ports:
      - 3000:3000
    environment:
      - PORT=3000
    image: railtelhrit.jfrog.io/ndhm-docker/hrp:latest
  healthid:
    build:
      context: .
      dockerfile: ./apps/healthid/Dockerfile
      args:
        - appname=healthid
    ports:
      - 3001:3000
    environment:
      - PORT=3000
      - MS_NDHM_CLIENT_HOST=ndhm-client
      - MS_NDHM_CLIENT_PORT=3000
    image: railtelhrit.jfrog.io/ndhm-docker/healthid:latest
  ndhm-client:
    build:
      context: .
      dockerfile: ./apps/microservice/ndhm-client/Dockerfile
      args:
        - appname=ndhm-client
    ports:
      - 3002:3000
    environment:
      - PORT=3000
    env_file:
      - .env
    image: railtelhrit.jfrog.io/ndhm-docker/ndhm-client:latest