version: '3.9'
services:
  hrp:
    build:
      context: .
      dockerfile: ./apps/hrp/Dockerfile
      args:
        - appname=hrp
    ports:
      - 3000:3000
    environment:
      - PORT=3000
    image: railtelhrit.jfrog.io/ndhm-docker/hrp:latest
  healthid:
    build:
      context: .
      dockerfile: ./apps/healthid/Dockerfile
      args:
        - appname=healthid
    ports:
      - 3001:3000
    environment:
      - PORT=3000
    image: railtelhrit.jfrog.io/ndhm-docker/healthid:latest