apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-pv
  labels:
    type: kafkalocal
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/kubernetes/pv/zookeeper"
