apiVersion: apps/v1
kind: Deployment
metadata:
  name: hip
  namespace: ndhm
spec:  
  selector:
    matchLabels:
      app: hip
  replicas: 2
  template:
    metadata:
      labels:
        app: hip
    spec:
      imagePullSecrets:
        - name: jfrogcred
      containers:        
      - name: hip
        image: railtelhrit.jfrog.io/ndhm-docker/hip:latest
        env:
          - name: "PORT"
            value: "3000"
          - name: "MS_NDHM_CLIENT_HOST"
            value: "ndhm-client-service"
          - name: "MS_NDHM_CLIENT_PORT"
            value: "3000"
          - name: "KAFKA_BROKER_ADDRESSLIST"
            value: "kafka-cluster-kafka-brokers.kafka:9092"
          - name: "CLIENT_ID"
            valueFrom:
              secretKeyRef:
                name: sandboxsecret
                key: CLIENT_ID
          - name: "CLIENT_SECRET"
            valueFrom:
              secretKeyRef:
                name: sandboxsecret
                key: CLIENT_SECRET
        resources:
          limits:
            memory: "128Mi"
            cpu: "600m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: hip-service
  namespace: ndhm
spec:
  selector:
    app: hip
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
