apiVersion: apps/v1
kind: Deployment
metadata:
  name: hiu
  namespace: ndhm
spec:  
  selector:
    matchLabels:
      app: hiu
  replicas: 2
  template:
    metadata:
      labels:
        app: hiu
    spec:
      imagePullSecrets:
        - name: jfrogcred
      containers:        
      - name: hiu        
        image: railtelhrit.jfrog.io/ndhm-docker/hiu:latest
        env:
          - name: "PORT"
            value: "3000"
          - name: "CLIENT_ID"
            valueFrom:
              secretKeyRef:
                name: sandboxsecret
                key: CLIENT_ID
          - name: "CLIENT_SECRET"
            valueFrom:
              secretKeyRef:
                name: sandboxsecret
                key: CLIENT_SECRET
        resources:
          limits:
            memory: "128Mi"
            cpu: "600m"        
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: hiu-service
  namespace: ndhm
spec:
  selector:
    app: hiu
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
